catalog/urls.py
import registration
from django.urls import path

from .views import (
    index,
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    EmployeeListView,
    EmployeeDetailView,
    EmployeeCreateView,
    EmployeeNumberUpdateView,
    EmployeeDeleteView,
    BrandListView,
    BrandCreateView,
    BrandUpdateView,
    BrandDeleteView,
    register_view
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "brand/",
        BrandListView.as_view(),
        name="brand-list",
    ),
    path(
        "brand/create/",
        BrandCreateView.as_view(),
        name="brand-create",
    ),
    path(
        "brand/<int:pk>/update/",
        BrandUpdateView.as_view(),
        name="brand-update",
    ),
    path(
        "brand/<int:pk>/delete/",
        BrandDeleteView.as_view(),
        name="brand-delete",
    ),
    path("products/", ProductListView.as_view(), name="product-list"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product-detail"),
    path("products/create/", ProductCreateView.as_view(), name="product-create"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product-update"),
    path("products/<int:pk>/delete/", ProductDeleteView.as_view(), name="product-delete"),
    path("employees/", EmployeeListView.as_view(), name="employee-list"),
    path(
        "employees/<int:pk>/", EmployeeDetailView.as_view(), name="employee-detail"
    ),
    path("employees/", EmployeeListView.as_view(), name="employee-list"),
    path(
        "employees/<int:pk>/", EmployeeDetailView.as_view(), name="employee-detail"
    ),
    path("employees/create/", EmployeeCreateView.as_view(), name="employee-create"),
    path(
        "employees/<int:pk>/update/",
        EmployeeNumberUpdateView.as_view(),
        name="employee-number",
    ),
    path(
        "employees/<int:pk>/delete/",
        EmployeeDeleteView.as_view(),
        name="employee-delete",
    ),
    path("register/", register_view, name="register"),
]

app_name = "catalog"

pc_components_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("accounts/", include("django.contrib.auth.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Brand(models.Model):
    name = models.CharField(max_length=255, unique=True)
    country = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Employee(AbstractUser):
    brand = models.ForeignKey(
        Brand,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name="employees"
    )
    employee_number = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name = "employee"
        verbose_name_plural = "employees"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("catalog:employee-detail", kwargs={"pk": self.pk})


class Product(models.Model):
    name = models.CharField(max_length=255, unique=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name="products")
    price = models.DecimalField(decimal_places=2, max_digits=10)
    in_stock = models.BooleanField(default=False)
    amount = models.IntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="products")
    managers = models.ManyToManyField(Employee, related_name="products", blank=True)

    def __str__(self):
        return self.name

catalog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from catalog.models import Product, Employee


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"


class EmployeeCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Employee
        fields = UserCreationForm.Meta.fields + (
            "employee_number",
            "first_name",
            "last_name",
        )

    def clean_employee_number(self):
        return validate_employee_number(self.cleaned_data["employee_number"])


class EmployeeNumberUpdateForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ["employee_number"]

    def clean_employee_number(self):
        return validate_employee_number(self.cleaned_data["employee_number"])


def validate_employee_number(employee_number):
    if len(employee_number) != 8:
        raise ValidationError("Employee number must be exactly 8 characters")
    if not employee_number[:3].isupper() or not employee_number[:3].isalpha():
        raise ValidationError("First 3 characters must be uppercase letters")
    if not employee_number[3:].isdigit():
        raise ValidationError("Last 5 characters must be digits")
    return employee_number



class ProductSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )


class EmployeeSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"}),
    )


class BrandSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )

catalog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Employee, Product, Brand
from .forms import (EmployeeCreationForm, ProductForm, EmployeeNumberUpdateForm,
                    ProductSearchForm, EmployeeSearchForm, BrandSearchForm)


@login_required
def index(request):
    num_products = Product.objects.count()
    num_employees = Employee.objects.count()
    num_brands = Brand.objects.count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    return render(request, 'catalog/index.html', {
        'num_products': num_products,
        'num_employees': num_employees,
        'num_brands': num_brands,
        'num_visits': num_visits,
    })



class BrandListView(LoginRequiredMixin, generic.ListView):
    model = Brand
    context_object_name = "brand_list"
    template_name = "catalog/brand_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(BrandListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name")
        context["search_form_brand"] = BrandSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Brand.objects.filter().order_by("id")
        form = BrandSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class BrandCreateView(LoginRequiredMixin, generic.CreateView):
    model = Brand
    fields = "__all__"
    success_url = reverse_lazy("catalog:brand-list")


class BrandUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Brand
    fields = "__all__"
    success_url = reverse_lazy("catalog:brand-list")


class BrandDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Brand
    success_url = reverse_lazy("catalog:brand-list")


class ProductListView(LoginRequiredMixin, generic.ListView):
    model = Product
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        name_param = self.request.GET.get("name")
        context["search_form_product"] = ProductSearchForm(
            initial={"name": name_param}
        )
        return context

    def get_queryset(self):
        queryset = Product.objects.all().order_by("id")
        form = ProductSearchForm(self.request.GET)
        if form.is_valid():
            name = form.cleaned_data.get("name")
            if name:
                return queryset.filter(name__icontains=name)
        return queryset


class ProductDetailView(LoginRequiredMixin, generic.DetailView):
    model = Product


class ProductCreateView(LoginRequiredMixin, generic.CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product-list")


class ProductUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product-list")


class ProductDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Product
    success_url = reverse_lazy("catalog:product-list")


class EmployeeListView(LoginRequiredMixin, generic.ListView):
    model = Employee
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        username = self.request.GET.get("username")
        context["search_form_employee"] = EmployeeSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = Employee.objects.all().order_by("id")
        form = EmployeeSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class EmployeeDetailView(LoginRequiredMixin, generic.DetailView):
    model = Employee
    queryset = Employee.objects.all().prefetch_related("products__brand")


class EmployeeCreateView(LoginRequiredMixin, generic.CreateView):
    model = Employee
    form_class = EmployeeCreationForm


class EmployeeNumberUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Employee
    form_class = EmployeeNumberUpdateForm
    success_url = reverse_lazy("catalog:employee-list")


class EmployeeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Employee
    success_url = reverse_lazy("")


def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("login")
    else:
        form = UserCreationForm()
    return render(request, "registration/register.html", {"form": form})

templates/catalog/brand_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container py-5 mt-7">
    <div class="row mb-4 align-items-center">
      <div class="col-md-8">
        <h2 class="mb-0 text-gradient text-primary font-weight-bold">Brand List</h2>
      </div>
      <div class="col-md-4 text-end">
        <a href="{% url 'catalog:brand-create' %}" class="btn btn-primary btn-sm">
          <i class="fas fa-plus me-1"></i> Create Brand +
        </a>
      </div>
    </div>

    <!-- Search Form -->
    <div class="card shadow-sm border-radius-xl mb-4">
      <div>
        <form method="get" action="{% url 'catalog:brand-list' %}"
              class="row g-2 align-items-center justify-content-center">
          <div class="col-md-6 col-sm-8">
            <div class="input-group input-group-outline input-group-sm">
              {{ search_form_brand|crispy }}
            </div>
          </div>
          <div class="col-md-2 col-sm-4">
            <button type="submit" class="btn btn-sm btn-outline-primary w-100 mt-3">
              <i class="fas fa-search me-1"></i> Search
            </button>
          </div>
        </form>
      </div>
    </div>

    {% if brand_list %}
      <div class="card shadow-lg border-radius-xl">
        <div class="card-body px-4 py-4">
          <div class="table-responsive">
            <table class="table align-items-center mb-0">
              <thead>
              <tr>
                <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7">ID</th>
                <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Name</th>
                <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Country</th>
                <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Update</th>
                <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Delete</th>
              </tr>
              </thead>
              <tbody>
              {% for brand in brand_list %}
                <tr>
                  <td class="text-sm">{{ brand.id }}</td>
                  <td class="text-sm">{{ brand.name }}</td>
                  <td class="text-sm">{{ brand.country }}</td>
                  <td>
                    <a href="{% url 'catalog:brand-update' pk=brand.id %}" class="text-primary font-weight-bold">
                      Update
                    </a>
                  </td>
                  <td>
                    <a href="{% url 'catalog:brand-delete' pk=brand.id %}" class="text-danger font-weight-bold">
                      Delete
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>

          <!-- Pagination -->
          {% if is_paginated %}
            <nav aria-label="Page navigation example">
              <ul class="pagination justify-content-center mt-4">
                {% if page_obj.has_previous %}
                  <li class="page-item">
                    <a class="page-link rounded-0" href="?page={{ page_obj.previous_page_number }}"
                       aria-label="Previous">
                      <span aria-hidden="true">&laquo;</span>
                      <span class="visually-hidden">Previous</span>
                    </a>
                  </li>
                {% else %}
                  <li class="page-item disabled">
          <span class="page-link rounded-0" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="visually-hidden">Previous</span>
          </span>
                  </li>
                {% endif %}

                {% for num in paginator.page_range %}
                  {% if page_obj.number == num %}
                    <li class="page-item active" aria-current="page">
                      <span class="page-link rounded-0">{{ num }}</span>
                    </li>
                  {% else %}
                    <li class="page-item">
                      <a class="page-link rounded-0" href="?page={{ num }}">{{ num }}</a>
                    </li>
                  {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                  <li class="page-item">
                    <a class="page-link rounded-0" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                      <span aria-hidden="true">&raquo;</span>
                      <span class="visually-hidden">Next</span>
                    </a>
                  </li>
                {% else %}
                  <li class="page-item disabled">
          <span class="page-link rounded-0" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="visually-hidden">Next</span>
          </span>
                  </li>
                {% endif %}
              </ul>
            </nav>
          {% endif %}

          <!-- /Pagination -->

        </div>
      </div>
    {% else %}
      <div class="alert alert-secondary text-center" role="alert">
        There are no brands in the service.
      </div>
    {% endif %}
  </div>
{% endblock %}

templates/catalog/employee_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container py-5 mt-7">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1 class="h3 text-gradient text-dark font-weight-bold">Employee: {{ employee.username }}</h1>
      <div>
        <a href="{% url 'catalog:employee-list' %}" class="btn btn-outline-primary btn-sm me-2">
          <i class="material-icons">arrow_back</i> Back
        </a>
        <a href="{% url 'catalog:employee-delete' pk=employee.id %}" class="btn btn-outline-danger btn-sm me-2">
          <i class="material-icons">delete</i> Delete
        </a>
        <a href="{% url 'catalog:employee-number' pk=employee.id %}" class="btn btn-outline-secondary btn-sm">
          <i class="material-icons">edit</i> Update employee number
        </a>
      </div>
    </div>

    <div class="card shadow-lg border-radius-xl">
      <div class="card-header bg-gradient-light text-dark">
        <h4 class="mb-0"><strong>{{ employee.username }}</strong></h4>
      </div>
      <div class="card-body">
        <dl class="row mb-0">
          <dt class="col-sm-4">First name</dt>
          <dd class="col-sm-8">{{ employee.first_name }}</dd>

          <dt class="col-sm-4">Last name</dt>
          <dd class="col-sm-8">{{ employee.last_name }}</dd>

          <dt class="col-sm-4">Employee number</dt>
          <dd class="col-sm-8">{{ employee.employee_number }}</dd>

          <dt class="col-sm-4">Is staff</dt>
          <dd class="col-sm-8">{{ employee.is_staff|yesno:"Yes,No" }}</dd>
        </dl>
      </div>
    </div>

    <div class="card shadow-lg border-radius-xl mt-4">
      <div class="card-header bg-gradient-light text-dark">
        <h4 class="mb-0">Brands</h4>
      </div>
      <div class="card-body">
        {% if employee.brand.all %}
          {% for brand in employee.brand.all %}
            <div class="mb-3 border-bottom pb-3">
              <p><strong>Name:</strong> {{ brand.name }}</p>
              <p><strong>Country:</strong> {{ brand.country }}</p>
              <p class="text-muted"><strong>ID:</strong> {{ brand.id }}</p>
            </div>
          {% endfor %}
        {% else %}
          <p>No brands!</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

templates/catalog/employee_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container py-5 mt-7">
    <div class="row mb-4 align-items-center">
      <div class="col-md-8">
        <h2 class="mb-0 text-gradient text-primary font-weight-bold">Employee List</h2>
      </div>
      <div class="col-md-4 text-end">
        <a href="{% url 'catalog:employee-create' %}" class="btn btn-primary btn-sm">
          <i class="fas fa-plus me-1"></i> Create Employee +
        </a>
      </div>
    </div>

    <!-- Search Form -->
    <div class="card shadow-sm border-radius-xl mb-4">
      <div>
        <form method="get" action="{% url 'catalog:employee-list' %}"
              class="row g-2 align-items-center justify-content-center">
          <div class="col-md-6 col-sm-8">
            <div class="input-group input-group-outline input-group-sm">
              {{ search_form_employee|crispy }}
            </div>
          </div>
          <div class="col-md-2 col-sm-4">
            <button type="submit" class="btn btn-sm btn-outline-primary w-100 mt-3">
              <i class="fas fa-search me-1"></i> Search
            </button>
          </div>
        </form>
      </div>
    </div>

    {% if employee_list %}
      <div class="card shadow-lg border-radius-xl">
        <div class="card-body px-4 py-4">
          <div class="table-responsive">
            <table class="table align-items-center mb-0">
              <thead>
              <tr>
                <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7">ID</th>
                <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Username</th>
                <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7">First Name</th>
                <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Last Name</th>
                <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Employee Number</th>
              </tr>
              </thead>
              <tbody>
              {% for employee in employee_list %}
                <tr>
                  <td class="text-sm">#{{ employee.id }}</td>
                  <td class="text-sm">
                    <a href="{{ employee.get_absolute_url }}" class="text-primary">
                      {{ employee.username }}{% if user == employee %} <small>(Me)</small>{% endif %}
                    </a>
                  </td>
                  <td class="text-sm">{{ employee.first_name }}</td>
                  <td class="text-sm">{{ employee.last_name }}</td>
                  <td class="text-sm">{{ employee.employee_number }}</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>

          <!-- Pagination -->
          {% if is_paginated %}
            <nav aria-label="Page navigation example">
              <ul class="pagination justify-content-center mt-4">
                {% if page_obj.has_previous %}
                  <li class="page-item">
                    <a class="page-link rounded-0" href="?page={{ page_obj.previous_page_number }}"
                       aria-label="Previous">
                      <span aria-hidden="true">&laquo;</span>
                      <span class="visually-hidden">Previous</span>
                    </a>
                  </li>
                {% else %}
                  <li class="page-item disabled">
                    <span class="page-link rounded-0" aria-label="Previous">
                      <span aria-hidden="true">&laquo;</span>
                      <span class="visually-hidden">Previous</span>
                    </span>
                  </li>
                {% endif %}

                {% for num in paginator.page_range %}
                  {% if page_obj.number == num %}
                    <li class="page-item active" aria-current="page">
                      <span class="page-link rounded-0">{{ num }}</span>
                    </li>
                  {% else %}
                    <li class="page-item">
                      <a class="page-link rounded-0" href="?page={{ num }}">{{ num }}</a>
                    </li>
                  {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                  <li class="page-item">
                    <a class="page-link rounded-0" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                      <span aria-hidden="true">&raquo;</span>
                      <span class="visually-hidden">Next</span>
                    </a>
                  </li>
                {% else %}
                  <li class="page-item disabled">
                    <span class="page-link rounded-0" aria-label="Next">
                      <span aria-hidden="true">&raquo;</span>
                      <span class="visually-hidden">Next</span>
                    </span>
                  </li>
                {% endif %}
              </ul>
            </nav>
          {% endif %}
          <!-- /Pagination -->

        </div>
      </div>
    {% else %}
      <div class="alert alert-secondary text-center" role="alert">
        There are no employees in the store.
      </div>
    {% endif %}
  </div>
{% endblock %}

templates/catalog/product_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container py-5 mt-7">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1 class="h3 text-gradient text-dark font-weight-bold">Product Detail</h1>
      <div>
        <a href="{% url 'catalog:product-list' %}" class="btn btn-outline-primary btn-sm me-2">
          <i class="material-icons">arrow_back</i> Back
        </a>
        <a href="{% url 'catalog:product-update' pk=product.id %}" class="btn btn-outline-secondary btn-sm me-2">
          <i class="material-icons">edit</i> Update
        </a>
        <a href="{% url 'catalog:product-delete' pk=product.id %}" class="btn btn-outline-danger btn-sm">
          <i class="material-icons">delete</i> Delete
        </a>
      </div>
    </div>

    <div class="card shadow-lg border-radius-xl">
      <div class="card-header bg-gradient-light text-white">
        <h4 class="mb-0"><strong>{{ product.name }}</strong></h4>
        <small class="text-dark">by <span class="text-dark">{{ product.brand.name }}</span></small>
      </div>
      <div class="card-body">
        <dl class="row mb-0">
          <dt class="col-sm-4">Price</dt>
          <dd class="col-sm-8">${{ product.price }}</dd>

          <dt class="col-sm-4">Amount</dt>
          <dd class="col-sm-8">{{ product.amount }}</dd>

          <dt class="col-sm-4">Category</dt>
          <dd class="col-sm-8">{{ product.category.name }}</dd>

          <dt class="col-sm-4">Stock Status</dt>
          <dd class="col-sm-8">
            {% if product.in_stock %}
              <span class="badge bg-gradient-success">In Stock</span>
            {% else %}
              <span class="badge bg-gradient-danger">Out of Stock</span>
            {% endif %}
          </dd>
        </dl>
      </div>
    </div>
  </div>
{% endblock %}

templates/catalog/product_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container py-5 mt-7">
    <div class="row mb-4 align-items-center">
      <div class="col-md-8">
        <h2 class="mb-0 text-gradient text-primary font-weight-bold">Product List</h2>
      </div>
      <div class="col-md-4 text-end">
        <a href="{% url 'catalog:product-create' %}" class="btn btn-primary btn-sm">
          <i class="fas fa-plus me-1"></i> Create Product +
        </a>
      </div>
    </div>

    <!-- Search Form -->
    <div class="card shadow-sm border-radius-xl mb-4">
      <div>
        <form method="get" action="{% url 'catalog:product-list' %}"
              class="row g-2 align-items-center justify-content-center">
          <div class="col-md-6 col-sm-8">
            <div class="input-group input-group-outline input-group-sm">
              {{ search_form_product|crispy }}
            </div>
          </div>
          <div class="col-md-2 col-sm-4">
            <button type="submit" class="btn btn-sm btn-outline-primary w-100 mt-3">
              <i class="fas fa-search me-1"></i> Search
            </button>
          </div>
        </form>
      </div>
    </div>

    {% if product_list %}
      <div class="card shadow-lg border-radius-xl">
        <div class="card-body px-4 py-4">
          <div class="table-responsive">
            <table class="table align-items-center mb-0">
              <thead>
              <tr>
                <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7">ID</th>
                <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Brand</th>
                <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Name</th>
                <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Price</th>
                <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Stock</th>
                <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Category</th>
              </tr>
              </thead>
              <tbody>
              {% for product in product_list %}
                <tr>
                  <td>
                    <a href="{% url "catalog:product-detail" pk=product.id %}"
                       class="text-primary text-sm font-weight-bold">
                      #{{ product.id }}
                    </a>
                  </td>
                  <td class="text-sm">{{ product.brand.name }}</td>
                  <td class="text-sm">{{ product.name }}</td>
                  <td class="text-sm">${{ product.price }}</td>
                  <td class="text-sm">
                    {% if product.in_stock %}
                      <span class="badge bg-gradient-success">In Stock</span>
                    {% else %}
                      <span class="badge bg-gradient-danger">Out of Stock</span>
                    {% endif %}
                  </td>
                  <td class="text-sm">{{ product.category.name }}</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>

          <!-- Pagination -->
          {% if is_paginated %}
            <nav aria-label="Page navigation example">
              <ul class="pagination justify-content-center mt-4">
                {% if page_obj.has_previous %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                      <span aria-hidden="true">&laquo;</span>
                      <span class="visually-hidden">Previous</span>
                    </a>
                  </li>
                {% else %}
                  <li class="page-item disabled">
                    <span class="page-link" aria-label="Previous">
                      <span aria-hidden="true">&laquo;</span>
                      <span class="visually-hidden">Previous</span>
                    </span>
                  </li>
                {% endif %}

                {% for num in paginator.page_range %}
                  {% if page_obj.number == num %}
                    <li class="page-item active" aria-current="page">
                      <span class="page-link">{{ num }}</span>
                    </li>
                  {% else %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                  {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                      <span aria-hidden="true">&raquo;</span>
                      <span class="visually-hidden">Next</span>
                    </a>
                  </li>
                {% else %}
                  <li class="page-item disabled">
                    <span class="page-link" aria-label="Next">
                      <span aria-hidden="true">&raquo;</span>
                      <span class="visually-hidden">Next</span>
                    </span>
                  </li>
                {% endif %}
              </ul>
            </nav>
          {% endif %}
          <!-- /Pagination -->

        </div>
      </div>
    {% else %}
      <div class="alert alert-secondary text-center" role="alert">
        There are no products in the catalog.
      </div>
    {% endif %}
  </div>
{% endblock %}